export const GET_ALL_PRESENTATIONS_SUCCESS = "GET_ALL_PRESENTATIONS_SUCCESS";
export const GET_PRESENTATION_SUCCESS = "GET_PRESENTATION_SUCCESS";
export const SET_TOTAL_STUDENTS = "SET_TOTAL_STUDENTS";
export const GET_PRESENTATION_GROUPS = "GET_PRESENTATION_GROUPS";
