const API_CODE_BY_SERVER = 9999;
const API_CODE_SUCCESS = 0;
const API_CODE_FAIL = 1;
const API_CODE_UNAUTHORIZED = 3;

module.exports = {
  API_CODE_BY_SERVER,
  API_CODE_SUCCESS,
  API_CODE_FAIL,
  API_CODE_UNAUTHORIZED
};
